---
# Web-serving VMs deployment playbook.

- name: configure web application nodes
  hosts: appservers
  sudo: yes
  roles:
    - common
    - php5-fpm
    - php-tools
    - user-account
    - git-repository
    - project
    - nginx

