---
# This playbook contains play that will install and configure PostgreSQL database.

- name: workaround to install postgresql with locale set
  shell: LANG={{ database_locale }} LC_COLLATE={{ database_locale }}  LC_CTYPE={{ database_locale }}  LC_MESSAGES={{ database_locale }} LC_MONETARY={{ database_locale }} LC_NUMERIC={{ database_locale }} LC_TIME={{ database_locale }} LC_ALL={{ database_locale }}  apt-get install -y postgresql

- name: install db server supporting packages
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2

- name: add postgres user to admin group
  user: name=postgres groups=admin append=yes

- name: update postgres db configuration
  template: src=postgresql.conf dest=/etc/postgresql/9.1/main/postgresql.conf

- name: update postgres client configuration
  template: src=pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf
  notify:
    - restart postgresql

- name: create a test database user
  sudo_user: postgres
  postgresql_user: user={{ database_user }} password={{ database_pass }}
  notify:
    - restart postgresql

- name: create main database
  sudo_user: postgres
  postgresql_db: name={{ database_name }} owner={{ database_user }} encoding=UTF8 lc_collate=en_US.UTF-8 lc_ctype=en_US.UTF-8

- name: create testing database (used in unit testing)
  sudo_user: postgres
  postgresql_db: name={{ database_name }}_test owner={{ database_user }} encoding=UTF8 lc_collate=en_US.UTF-8 lc_ctype=en_US.UTF-8
